version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::590672219346:user/dummy-aws-sam-cli-user"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-10Q3R2PSJD8Z1"
cloudformation_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-CloudFormationExecutionR-1GX95NEQU406B"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-nup5nj1b9dfb"
image_repository = ""
region = "eu-west-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-Y364KSM6UVRV"
cloudformation_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1VU2ZQCJIDV7W"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1l6ytovke2ois"
image_repository = ""
region = "eu-west-1"
