version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::354087173127:user/aws-sam-cli-managed-staging-pipeline-PipelineUser-XNVC74M57BVU"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-1DLBUQ6UNNQX7"
cloudformation_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-CloudFormationExecutionR-1BGDI9HEH35O"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-au1hjr2128bw"
image_repository = ""
region = "eu-west-3"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-125II9ETGPTND"
cloudformation_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1X9T0LS7UEXZO"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-204szu1b7wru"
image_repository = ""
region = "eu-west-3"
