version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::590672219346:user/dummy-aws-sam-cli-user"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-1W91IZUIN3R0"
cloudformation_execution_role = "arn:aws:iam::354087173127:role/aws-sam-cli-managed-test-CloudFormationExecutionR-126US6A1Q5919"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-lzo10472ev2o"
image_repository = ""
region = "us-west-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-KIJERBE65HMF"
cloudformation_execution_role = "arn:aws:iam::670535138659:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-MCZJRJBQPTXE"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-8v32xa83djno"
image_repository = ""
region = "us-west-2"
