version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pipeline-trigger"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k9jc8e8yubkd"
s3_prefix = "pipeline-trigger"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
